name: Lighthouse CI

on:
  workflow_call:

jobs:
  lighthouse_audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      - name: Run Lighthouse Audit
        run: lhci autorun  --upload.target=temporary-public-storage

      - name: Output Lighthouse Report URL
        run: |
          echo "Lighthouse Report available at: https://storage.googleapis.com/lighthouse-ci-temp/index.html"
